# -*- coding: utf-8 -*-
"""faceRecognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yz9T7CimWFvgMYIs3IDL2EmzwOSvOKqC
"""

!sudo apt-get install opencv

!pip install opencv-python

import cv2
import dlib
from google.colab.patches import cv2_imshow
import matplotlib as plt
import seaborn

imagem = cv2.imread("/content/px-people.jpg")
cv2_imshow(imagem)

image_gray = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)
classificador = cv2.CascadeClassifier("/content/haarcascade_frontalface_default.xml")
faces = classificador.detectMultiScale(image_gray, 1.3, 5)
len(faces)

imagem_copy = imagem.copy()

for (x, y, w, h) in faces:
  cv2.rectangle(imagem_copy, (x,y), (x+w, y+h), (255,255,0), 2)
cv2_imshow(imagem_copy)

face_imagem = 0
for (x, y, w, h) in faces:
  face_imagem += 1
  imagem_roi = imagem[y:y+h, x:x+w]
  cv2.imwrite("face_" + str(face_imagem) + ".jpg", imagem_roi)
  cv2_imshow(imagem_roi)

